version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7

jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: test dependencies
          command: sudo pip install tox
      - run:
          name: test
          command: tox
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
